# To add to your shell profile (i.e. ~/.profile)
#
# Set data
export DB_USERNAME="asdf"
export DB_PASSWORD="asdf"
export DB_DATABASE="asdf"
export DB_HOST="asdf.us-east-1.rds.amazonaws.com"
export DB_DIALECT="postgres"
export AWS_REGION="us-east-1"
export AWS_PROFILE="default"
export AWS_MEDIA_BUCKET="asdf"
export JWT_SECRET=" "
